/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.expedisi;

import java.awt.event.ActionListener;
import java.sql.Date;
import java.sql.ResultSet;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import koneksi.Database;
import model.Aplikasi;
import model.View;

/**
 *
 * @author Kurniawan
 */
public class StatusAntar extends javax.swing.JFrame implements View {

    /**
     * Creates new form StatusAntar
     */
    public StatusAntar() {
        initComponents();
    }
    private JComboBox cbStat;
    private JComboBox cbKet;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tgl = new de.wannawork.jcalendar.JCalendarComboBox();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Status Antar"));

        jLabel1.setText("Masukkan Tanggal ");

        btnCari.setText("Search");

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb);

        btnCancel.setText("Cancel");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCari, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addGap(29, 29, 29)
                                .addComponent(btnUpdate)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCari)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Aplikasi app = new Aplikasi();
    model.transaksi tr = new model.transaksi();
model.transaksi tran = new model.transaksi();

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            app.updateStatusAntar(tran.getNoResi(), getCbStat(), getCbKet());
            JOptionPane.showMessageDialog(null, "Update Status Antar Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        // TODO add your handling code here:
        tran.setNoResi(tb.getValueAt(tb.getSelectedRow(), 0).toString());
        //System.out.print(tb.getValueAt(tb.getSelectedRow(), 0)+" ");
       /* tb.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        @Override
        public void valueChanged(ListSelectionEvent event) {
            // do some actions here, for example
            // print first column value from selected row
            tran.setNoResi(tb.getValueAt(tb.getSelectedRow(), 0).toString());
            System.out.print(tb.getValueAt(tb.getSelectedRow(), 0)+" ");
        }
    });*/
    }//GEN-LAST:event_tbMouseClicked
    public void tampilTransaksi(Date tgl) {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("No. Resi");
        tabel.addColumn("Tanggal Cetak");
        tabel.addColumn("Besar Uang");
        tabel.addColumn("Nama Pengirim");
        tabel.addColumn("Nama Penerima");
        tabel.addColumn("Status Antar");
        cbStat = new JComboBox();
        cbStat.addItem("Berhasil");
        cbStat.addItem("Gagal");
        tabel.addColumn("Keterangan");
        try {
            Database db = new Database();

            String s = "select * from transaksi where tglCetak='" + tgl + "'";
            ResultSet res = db.getData(s);
            while (res.next()) {
                tr.setNoResi(res.getString(1));
                tr.setNamaPengirim(res.getString(2));
                tr.setNamaPenerima(res.getString(6));
                tr.setTglCetak(res.getDate(10));
                tr.setBesarUang(res.getInt(11));
                tabel.addRow(new Object[]{res.getString(1), res.getDate(10), res.getInt(11),
                    res.getString(2), res.getString(6), res.getString(13), res.getString(15)});

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Tampil Data");
        }
        tb.setModel(tabel);
        tb.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(cbStat));
        cbKet = new JComboBox();
        cbKet.addItem("");
        cbKet.addItem("Alamat Tidak Jelas");
        cbKet.addItem("Pindah Alamat");
        cbKet.addItem("Ditolah penerima");
        tb.getColumnModel().getColumn(6).setCellEditor(new DefaultCellEditor(cbKet));
        if (cbStat.getSelectedItem().toString().equals("Gagal")) {
            tb.getColumnModel().getColumn(6).setCellEditor(new DefaultCellEditor(cbKet));
        }

    }

    public String getCbStat() {
        return cbStat.getSelectedItem().toString();
    }

    public String getCbKet() {
        return cbKet.getSelectedItem().toString();
    }

    public void setCbStat(Object cbStat) {
        this.cbStat.setSelectedItem(cbStat);
    }

    public void setCbKet(Object cbKet) {
        this.cbKet.setSelectedItem(cbKet);
    }

    public Date getTgl() {
        Date tglC = new Date(tgl.getDate().getTime());
        return tglC;
    }

    public void setTgl(Date tgl) {
        this.tgl.setDate(tgl);
    }

    public Object getBtnCancel() {
        return btnCancel;
    }

    public Object getBtnCari() {
        return btnCari;
    }

    public Object getBtnUpdate() {
        return btnUpdate;
    }

    @Override
    public void addListener(ActionListener e) {
        btnCancel.addActionListener(e);
        btnCari.addActionListener(e);
        btnUpdate.addActionListener(e);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb;
    private de.wannawork.jcalendar.JCalendarComboBox tgl;
    // End of variables declaration//GEN-END:variables
}
